sudo: required
dist: trusty
group: deprecated-2017Q4
language: php
php:
- 7.2
services:
- docker
os:
- linux
before_script:
- docker --version
- docker-compose --version
script:
- docker-compose build
- docker images
- docker-compose up -d
- sleep 20
- docker ps
- curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200
- curl --retry 10 --retry-delay 5 -v http://127.0.0.1:9200
- curl -XPUT 'http://127.0.0.1:9200/blog/user/khanh' -d '{ "name" : "Khanh" }'
- curl -XPUT 'http://127.0.0.1:9200/blog/post/1' -d '{"user": "khanh", "date": "2018-03-21","body": "Search is hard","title": "Test"}'
- curl -XPUT 'http://127.0.0.1:9200/blog/post/2' -d '{"user": "khanh", "date": "2018-03-21","body": "Search should be easy","title": " :v :v :v "}'
# after_success:
# - docker login -u $DOCKER_USER -p $DOCKER_PWD
# - docker push khanhnv/lar_circleci
env:
  global:
  - secure: M44NVp3+BfClPJp5jDvNXb7havgzEMuJx0nBNh2GxT4CUOax4KnwRNwUcFYJR2i+12utXbs4gpC/sGSVhhos3GIW/dRrnEw0wJUwtRwXRq8ZBq2bX8AlemjLiTuFYnCpg7PjldX7dqg3i8s7wkTHcUDwCRzoN0NgK+Q5hXWpSD3ho47BfWX1F8AmmGXSH64Lk1JGn47hUDElMtgX/gx+iwzYeVRS2kA35fSkiNB/ddhBUpVmp/DA18VpktxIcghl4ACK9z0frYZgqf/uqPFfRI/H0O9GkRZOK7gzjxSoPP329NTDzVBPICREjv2/oKIf/LETXuO0pzKeR6XDTL2ylZ7VzNt0qvzrOWn8WZKpvUlmqoDZaIwQZRk8F/421eujqCFN7diuZ2sJqmrgX7aEDC+jb2R6JPDTe8fuqTkBim5ZoC3Z7h64CqXwwESEofQhqor25TzDpdO99xq2TrC3TzV2gxRg1oInFSUsKKBvBsRHCrLf1a+aHp15H13uI4jYrwHigeVxrsvBc3VMRJBfZkoTQs530sdwe06/XyeqSr0u3pbnsnQr9R4WPb5rh2/nUDMI8cBF7R3pKkIfalf//tgaHatQOduDApk6q5vIpg7+j3wwfGd5w4j/q9zTBbNLUql49tEuiprr3hrLNwKPSmeMJTubuEfHrpfzWpB6tOQ=
  - secure: M/BN1bPvxayHFswC7js8PzX815221ZI7w3d8QT8YXAZR4FrXnuSw9KMXy5h0akRZEaK0iwIH7igf3kltdURpeVgtDx5cDKWNMLGTDTBpyyqh3SMgjzrIujwopYl1TfENJS/yKrpTp0ueH36BV6k4Xx5Q8XMs2itKSdfgYisLImPArxklKb/FYT6uOkZLZ4ROUqljz7k+9DkjaVES9HkpuaA6+U/DarkP+Y4nZaBV8bitJCoqQYZxn4s6YaWTIkHgFlD5ecVm13V4ks+znYpXzPkjuOYWKAq/Aym9WWrduI6UJSWlAbVQOZb928VzNZvSpMQdTuJ+D49fzfgxD/lKLlkkr60dJaTarckSgkhP0HJGCo4YcVrzA09ssyaIguohBawjQ1NKeiIdVbYrdAE3PjKlC9zTFJzU1iBb75aG2KvStYSQ5jNBTrAo29r8/5V2t2a6eyYcRQIsMUbWNsP900OM3fwJCMm5h9ml9XO34eBDxavVS64FHUH4+S9fsgDKN6xzXSDszFCjvx4hH7yuKyBTdTbXcMJ8nDC7Z7kifdKAuYMMESxIgOGHpXt37eyLt4LzNT5GY7xkNsVVXNi/8svHHyrqETjiPTXIyZ9bF0/DWoD1zeN+k26C/xxqJVdvAOUbyPFStZoAFSVET4WC4p/d5UOp2VhiMtcjmTUw4kY=