version: '2'

services:
  php7:
    build:
      context: ./php7
    image: khanhnv/php7:latest
    volumes:
      - ./html:/var/www/html
      - ./php7/supervisor/conf.d:/etc/supervisor/conf.d
      - ./php7/supervisor/logs:/var/log/supervisor
      - ./php7/supervisor/cache:/var/log/cache
    ports:
      - "9000:9000"
    links:
      - mariadb
      - mongodb
      - elastic
      - sqlite
      - rabbitmq
    depends_on:
      - mariadb
      - mongodb
      - elastic
      - sqlite
      - rabbitmq
    extra_hosts:
      - "mail.tuoitre.com.vn:192.168.161.170"
    working_dir: /var/www/html
    networks:
      - network_custom

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - network_custom

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/db:/data/data
    ports:
        - 27017:27017
    networks:
      - network_custom

  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
        - network_custom

  elastic:
    build: 
        context: ./elastic
    image: khanhnv/elastic:v1.76
    volumes:
      - ./elastic/logs:/var/log/elasticsearch
    ports:
      - "9200:9200"
    networks:
        - network_custom
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - network_custom
  
  sqlite:
    build:
      context: ./sqlite
    image: khanhnv/sqlite:alpine
    stdin_open: true
    tty: true
    volumes:
      - ./sqlite/db/:/root/data/
    networks:
      - network_custom

networks:
  network_custom:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.0.1
